version: 2.1
orbs:
  node: circleci/node@5.0.2
  eb: circleci/aws-elastic-beanstalk@2.0.1
  aws-cli: circleci/aws-cli@3.1.1
jobs:
  frontend:
    working_directory: ~/app/udagram/udagram-frontend
    executor: node/default
    steps:
    # install node and checkout code
      - node/install:
          node-version: '14.15'
      - eb/setup
      - aws-cli/install
      - checkout
      - run:
          name: Install Front-End Dependencies
          command: npm install
      - run:
          name: Build Frontend
          command: npm run build
      - aws-cli/install
      - eb/setup
      - run:
          name: Deploy Frontend
          command: npm run deploy
  server:
    working_directory: ~/app/udagram/udagram-api
    executor: node/default
    steps:
      - aws-cli/install
      - eb/setup
      - checkout
      - run:
          name: Install Back-End Dependencies
          command: npm install
      - run:
          name: Build Backend
          command: npm run build
      - run:
          name: Deploy Server
          command: npm run deploy
workflows:
  build_and_deploy:
    jobs:
      - frontend
      - server
