version: 2.1
orbs:
  node: circleci/node@5.0.2
  eb: circleci/aws-elastic-beanstalk@2.0.1
  aws-cli: circleci/aws-cli@3.1.1
jobs:
  frontend:
    working_directory: ~/app/udagram/udagram-frontend
    executor: node/default
    steps: 
      - checkout:
          path: ~/app
      - node/install:
          install-yarn: true
          node-version: '16.13'
      - run: node --version
      - node/install-packages:
          app-dir: ~/app/udagram/udagram-frontend
      - run:
          name: Build Frontend
          command: npm run build
      - aws-cli/install
      - eb/setup
      - run:
          name: Deploy Frontend
          command: npm run deploy
  server:
    working_directory: ~/app/udagram/udagram-api
    executor: node/default
    steps:
      - checkout:
          path: ~/app
      - node/install-packages:
          app-dir: ~/app/udagram/udagram-api
      - aws-cli/install
      - eb/setup
      - run:
          name: Deploy Server
          command: npm run build && eb init udagram-api --region ${AWS_DEFAULT_REGION} --platform node.js && eb use udagram-api-dev && eb deploy
workflows:
  build_and_deploy:
    jobs:
      - frontend
      - server
