version: 2.1
orbs:
  node: circleci/node@5.0.2
  eb: circleci/aws-elastic-beanstalk@2.0.1
  aws-cli: circleci/aws-cli@3.1.1
jobs:
  frontend:
    working_directory: ~/app/udagram/udagram-frontend
    executor: node/default
    steps:
      - checkout:
          path: ~/app
      - node/install-packages:
          app-dir: ~/app/udagram/udagram-frontend
      - aws-cli/install
      - run:
          name: Build Frontend
          command: npm run build
      - aws-cli/install
      - run:
          name: Deploy Frontend
          command: command: aws s3 cp --recursive --acl public-read ./www s3://udagram-reema/
  server:
    working_directory: ~/app/udagram/udagram-api
    executor: node/default
    steps:
      - checkout:
          path: ~/app
      - node/install-packages:
          app-dir: ~/app/udagram/udagram-api
      - aws-cli/install
      - run:
          name: Deploy Server
          command: |-
            aws s3 cp ./www/Archive.zip s3://elasticbeanstalk-us-east-1-527335774654/
            aws elasticbeanstalk create-application-version --application-name udagram-api --version-label <<pipeline.git.revision>> --source-bundle S3Bucket="s3://elasticbeanstalk-us-east-1-527335774654/",S3Key="Archive.zip"
            aws elasticbeanstalk update-environment --application-name udagram-api --environment-name udagram-api-dev --version-label <<pipeline.git.revision>>
workflows:
  build_and_deploy:
    jobs:
      - frontend
      - server
